# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmc < Formula
  desc "CoinMarketCap CLI - cryptocurrency data at your fingertips"
  homepage "https://github.com/coinmarketcap-official/CoinMarketCap-CLI"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_darwin_amd64.tar.gz"
      sha256 "215c94054c92de20176348ab38c45363db68cf16f96127ce2ed7262263c06a9a"

      define_method(:install) do
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_darwin_arm64.tar.gz"
      sha256 "d88e13ed176a1235b7d6257bc9d6353e81600ad968ab2911bf75a6bd1562d32c"

      define_method(:install) do
        bin.install "cmc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_linux_amd64.tar.gz"
      sha256 "5fed093fd8bfd7937423bd7dba854fc40daac7461a0c4147987d261e7649bb37"
      define_method(:install) do
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coinmarketcap-official/CoinMarketCap-CLI/releases/download/v0.1.0/cmc_0.1.0_linux_arm64.tar.gz"
      sha256 "7f2ba97c34067a21fb6d24ad6b4214687e377e4aa69698abca93f6f81d6e099c"
      define_method(:install) do
        bin.install "cmc"
      end
    end
  end

  test do
    system "#{bin}/cmc", "version"
  end
end
