# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cmc < Formula
  desc "CoinMarketCap CLI - cryptocurrency data at your fingertips"
  homepage "https://github.com/coinmarketcap-official/CMC-CLI"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/coinmarketcap-official/CMC-CLI/releases/download/v0.1.0/cmc_0.1.0_darwin_amd64.tar.gz"
      sha256 "7fad1614ac53a7d4648785d5070714165a07a595dfd2bcb12dc71852706682a8"

      define_method(:install) do
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/coinmarketcap-official/CMC-CLI/releases/download/v0.1.0/cmc_0.1.0_darwin_arm64.tar.gz"
      sha256 "0105f97485b65ef284fe8c26e2016a0d3ad2e3ef5bcb1468df730d3df26393d5"

      define_method(:install) do
        bin.install "cmc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/coinmarketcap-official/CMC-CLI/releases/download/v0.1.0/cmc_0.1.0_linux_amd64.tar.gz"
      sha256 "db72d982707a66c545f87d913033296fb1568052fe9a39b56fac996377548a6f"
      define_method(:install) do
        bin.install "cmc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coinmarketcap-official/CMC-CLI/releases/download/v0.1.0/cmc_0.1.0_linux_arm64.tar.gz"
      sha256 "1439d2fdae8f824d5152301908165dd427df4920e2c50723b47944c91ee3d2bd"
      define_method(:install) do
        bin.install "cmc"
      end
    end
  end

  test do
    system "#{bin}/cmc", "version"
  end
end
